# Generated by Django 3.1.5 on 2021-01-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageOffersCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemOffer', models.CharField(max_length=100)),
                ('itemImage', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
