# Generated by Django 3.1.5 on 2021-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageofferscarousel',
            name='itemDescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
